### ISSUE TITLE
Unable to focus element inside shadowRoot

### ISSUE THREAD

**Issue by toshegg** [predixdesignsystem/px-modal#27]
Example JSFiddle: https://jsfiddle.net/ze0dpj85/3/

## Expected behavior:

"Button inside shadow DOM" is focused by default and is focusable with Tab or Shift-Tab.

## Actual behavior:

Unable to focus "Button inside shadow DOM".

## Steps to reproduce the problem:

* Create a custom element with a button.
* Pass the element to a modal's body through a slot.
* Try to focus the button.
* Unable to focus the button.

## Screenshots

![peek 2018-01-25 17-02](https://user-images.githubusercontent.com/5630034/35394927-aa3628a6-01f1-11e8-9ec9-cc0e575ccebf.gif)

**Comment by nonmetalhail** [comment]
Isnt this up to the end developer to put a `tabindex` on whatever content they shove into a slot? I see no way for us to handle this

**Comment by Toshegg** [comment]
@nonmetalhail, actually, no, `tabindex` doesn't work because px-modal handles all tab events in this method:

https://github.com/PredixDev/px-modal/blob/74afbada164b509a69f756e34d08c425e15f2cdb/px-modal.html#L314

I think the issue can be solved by adding a recursive shadowDom check to this method:

https://github.com/PredixDev/px-modal/blob/74afbada164b509a69f756e34d08c425e15f2cdb/px-modal.html#L295

**Comment by mdwragg** [comment]
Sounds like you're really close to it @Toshegg can you propose a pull request demonstrating the functionality you need?

Thanks.

**Comment by davidrleonard** [comment]
I think I understand the issue. It happens if you have a DOM structure like this:

```
<px-modal header="Confirm delete" accept-text="Cancel" reject-text="Permanently Delete Record">
  <div slot="body">
    <my-magic-component></my-magic-component>
    <button>Native Button</button>
  </div>
</px-modal>
```

And `my-magic-component` has this template:

```
<template>
  <button>Button inside Shadow DOM</button>
</template>
```

As far as I understand things, we can't solve for this use case. Web component's API contracts are designed to discourage the world from digging around inside unknown component's shadow roots. If we wanted to implement this, we'd have to walk the tree of our composed DOM children, pierce each shadow root with JS, and keep piercing on down collecting anything with a tabindex. That doesn't seem like a good idea.

Instead the `my-magic-component` should probably have a tabindex on it that places it in the tab order. `my-magic-component` should then listen for focus events and auto focus on its internal shadow DOM button. If `my-magic-component` has the attribute `tab-index="0"` it will automatically be picked up by the modal's `_getFocusableElements()` method and will be added as a focus candidate when the user tabs through the modal.

Let me know if you know of another way of handling this.

**Comment by toshegg** [comment]
@davidrleonard, I would suggest using an idea from iron-focusables-helper:

https://github.com/PolymerElements/iron-overlay-behavior/blob/b7afaae994d527c8582d6ae8a2694e81c571e092/iron-focusables-helper.html#L104

They are using a recursive check of shadow doms of nested elements in order to produce right focus behavior.

This can be fixed once in px-modal. Otherwise, each developer should keep in mind that **every** component inside px-modal needs to implement the fix that you are describing (a functionality to operate focus), because of your code that handles tab button:

https://github.com/PredixDev/px-modal/blob/74afbada164b509a69f756e34d08c425e15f2cdb/px-modal.html#L314

Yet another option can be removing this code from px-modal, what will relieve developers from making an extra code for each component.

**Comment by mdwragg** [comment]
@toshegg, say again, looks like you know you're way around this. Want to help us make this better with a PR? Thanks.
