### ISSUE TITLE
Layer issues in Safari and Chrome mobile

### ISSUE THREAD

**Issue by jbilyalov** [predixdesignsystem/px-modal#29]
- open predix-ui.com on iPhone 6 in Safari or Chrome
- navigate to modal component
- click "Open Modal" button
- Instead of being always on top, the modal opens in a window that appears to be under the page. When you scroll the page, it covers the modal.

**Comment by jbilyalov** [comment]
Still seeing the same effect. Modal appears behind the page. It looks like a window or frame that you can move to different parts of modal

**Comment by randyaskin** [comment]
Yeah I know, that's why I haven't closed this yet.

**Comment by MichaelZaporozhets** [comment]
I've had a look into this and discovered that the issue needs to be resolved further up the chain.

This is a known ios bug where -webkit-overflow-scrolling: touch; will wreak havoc on fixed positioned elements within it. Unfortunately there is no 'real' workaround for this issue- other than to switch back to default scrolling behaviour. 

I will close this issue for the time being, since this is a bug with predix-ui.com rather than this component, I'll follow up to propose a change therein.
